/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_bdd;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author tiago145
 */
public class tela_principal extends javax.swing.JFrame {

    private String usuario;
    private String url;
    private String senha;
    /**
     * Creates new form tela_principal
     * @param usr
     * @param pss
     * @param urls
     */
    public tela_principal(String usr, String pss, String urls) {
        initComponents();
        usuario = usr;
        senha = pss;
        url = urls;
        //System.out.println("Recebi:" + url + " " + usuario + " " + senha + " " + nome_db);
        
        carrega_arvore();
    }
    
    private void carrega_arvore()
    {
        try {
            //Faz a conexao e rebece os metadados
            Connection con = DriverManager.getConnection(url, usuario, senha);
            DatabaseMetaData meta = con.getMetaData();
            
            DefaultTreeModel modelo;
            
            //Tabelas e schemas
            ResultSet tabelas = meta.getTables(null, null, null, new String[]{"TABLE"});
            while(tabelas.next())
            {
                System.out.println("Database: " + tabelas.getString(1));
                System.out.println("Tabela: " + tabelas.getString("TABLE_NAME"));
                
                //Colunas
                ResultSet colunas = meta.getColumns(null, null, tabelas.getString("TABLE_NAME"), null);
                while(colunas.next())
                {
                    System.out.println("Campo: " + colunas.getString("COLUMN_NAME"));
                }
                
                //Chaves de cada coluna
                ResultSet chaves = meta.getPrimaryKeys(null, null, tabelas.getString("TABLE_NAME"));
                while(chaves.next())
                {
                    System.out.println("Chave primaria: " + chaves.getString("COLUMN_NAME"));
                }
                System.out.println("");
            }
        } catch (SQLException ex) {
            System.out.println("Erro db: " + ex);
        }
        
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Bases de dado");
        raiz.add(new DefaultMutableTreeNode("filho"));
        modelo = (DefaultTreeModel)arvore.getModel();
        modelo.setRoot(raiz);
        arvore.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto_tela_inicial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arvore = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botao_exportar = new javax.swing.JButton();
        botao_executar = new javax.swing.JButton();
        botao_limpar = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto_tela_inicial.setBackground(new java.awt.Color(255, 255, 51));
        texto_tela_inicial.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        texto_tela_inicial.setForeground(new java.awt.Color(51, 51, 51));
        texto_tela_inicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto_tela_inicial.setText("Banco de dados - ");

        arvore.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arvore.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arvore.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                arvoreAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(arvore);

        jTable1.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Digite sua query:");
        jScrollPane3.setViewportView(jTextArea1);

        botao_exportar.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_exportar.setText("Exportar CSV");

        botao_executar.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_executar.setText("Executar query");

        botao_limpar.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_limpar.setText("Limpar");

        botao_voltar.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_voltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(texto_tela_inicial)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_exportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_voltar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_executar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_limpar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_tela_inicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_executar)
                            .addComponent(botao_limpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_exportar)
                    .addComponent(botao_voltar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arvoreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_arvoreAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_arvoreAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arvore;
    private javax.swing.JButton botao_executar;
    private javax.swing.JButton botao_exportar;
    private javax.swing.JButton botao_limpar;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel texto_tela_inicial;
    // End of variables declaration//GEN-END:variables
}
