/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_bdd;

import java.sql.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tiago145
 */
public class tela_inicial extends javax.swing.JFrame {

    private String usuario;
    private String url;
    private String senha;
    private String nome_db;
    /**
     * Creates new form tela_inicial
     */
    public tela_inicial() {
        initComponents();
        //Inicializa as variaveis
        try {
        //Abre o arquivo de inicializacao
        FileReader arq = new FileReader("./init.txt");
        BufferedReader b = new BufferedReader(arq);
        
        String linha;
        
        //Se tiver a primeira linha
        if((linha = b.readLine()) != null)
        {
            //Caso usuario tenha selecionado lembrar, preenche os dados anteriores
            if(linha.charAt(0) == '1')
            {
                usuario = b.readLine();
                senha = b.readLine();
                url = b.readLine();
                campo_usuario.setText(usuario);
                campo_senha.setText(senha);
                check_lembrar.setSelected(true);
                
                if(url.charAt(5) == 'm')
                    botao_mysql.setSelected(true);
                else
                    botao_postgre.setSelected(true);
            }
        }
        
        } catch(IOException e1) {
            System.out.println("Erro: " + e1);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        texto_tela_inicial = new javax.swing.JLabel();
        botao_mysql = new javax.swing.JToggleButton();
        texto_bdd = new javax.swing.JLabel();
        botao_postgre = new javax.swing.JToggleButton();
        texto_usuario = new javax.swing.JLabel();
        campo_usuario = new javax.swing.JTextField();
        texto_senha = new javax.swing.JLabel();
        botao_entrar = new javax.swing.JButton();
        check_lembrar = new javax.swing.JCheckBox();
        campo_senha = new javax.swing.JTextField();

        jToggleButton2.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jToggleButton2.setText("MySQL");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1024, 600));

        texto_tela_inicial.setBackground(new java.awt.Color(255, 255, 51));
        texto_tela_inicial.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        texto_tela_inicial.setForeground(new java.awt.Color(51, 51, 51));
        texto_tela_inicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto_tela_inicial.setLabelFor(texto_tela_inicial);
        texto_tela_inicial.setText("Tela inicial");

        botao_mysql.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_mysql.setText("MySQL");
        botao_mysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_mysqlActionPerformed(evt);
            }
        });

        texto_bdd.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        texto_bdd.setText("Banco de dados:");

        botao_postgre.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_postgre.setText("PostgreSQL");
        botao_postgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_postgreActionPerformed(evt);
            }
        });

        texto_usuario.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        texto_usuario.setText("Usuário:");

        campo_usuario.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N

        texto_senha.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        texto_senha.setText("Senha:");

        botao_entrar.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        botao_entrar.setText("Entrar");
        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });

        check_lembrar.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        check_lembrar.setText("Lembre de mim");

        campo_senha.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(texto_tela_inicial))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texto_bdd)
                                    .addComponent(texto_usuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao_mysql)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botao_postgre))
                                    .addComponent(campo_usuario)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(texto_senha)
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao_entrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(check_lembrar)))))))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_tela_inicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_bdd)
                    .addComponent(botao_mysql)
                    .addComponent(botao_postgre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_usuario)
                    .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_senha)
                    .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_entrar)
                    .addComponent(check_lembrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_mysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_mysqlActionPerformed
        if(botao_mysql.isSelected())
            botao_postgre.setSelected(false);
    }//GEN-LAST:event_botao_mysqlActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void botao_postgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_postgreActionPerformed
        if(botao_postgre.isSelected())
            botao_mysql.setSelected(false);
    }//GEN-LAST:event_botao_postgreActionPerformed

    private void campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_senhaActionPerformed

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        usuario = campo_usuario.getText();
        senha = campo_senha.getText();
        if(botao_mysql.isSelected())
        {
            url = "jdbc:mysql://localhost/";
        }
        if(botao_postgre.isSelected())
        {
            url = "jdbc:postgresql://localhost/";
        }
        
        try {
            FileWriter arq = new FileWriter("./init.txt");
            if(check_lembrar.isSelected() == false)
            {
                arq.write("0");
                arq.close();
            }
            else
            {
                arq.write("1\n");
                arq.write(usuario + "\n");
                arq.write(senha + "\n");
                arq.write(url + "\n");
                arq.close();
            }
                
        } catch (IOException ex) {
            System.out.println("Erro: " + ex);
        }
        tela_principal principal = new tela_principal(usuario, senha, url);
        principal.show();
        dispose();
        
    }//GEN-LAST:event_botao_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JToggleButton botao_mysql;
    private javax.swing.JToggleButton botao_postgre;
    private javax.swing.JTextField campo_senha;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JCheckBox check_lembrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel texto_bdd;
    private javax.swing.JLabel texto_senha;
    private javax.swing.JLabel texto_tela_inicial;
    private javax.swing.JLabel texto_usuario;
    // End of variables declaration//GEN-END:variables
}
